var json_PENDIDIKAN_12 = {
"type": "FeatureCollection",
"name": "PENDIDIKAN_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 008 Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.442101, -0.356025 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 01 Sebemban", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.459054, -0.295552 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 006 Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.488056, -0.316296 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SMP Terbuka Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "3", "REMARK": "Pendidikan Menengah Pertama", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "2", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.485394729000063, -0.316582327999924 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SMA Negeri 1 Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "2", "REMARK": "Pendidikan Menengah Umum", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "2", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.47988, -0.314699 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SMA Negeri 1 Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "2", "REMARK": "Pendidikan Menengah Umum", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "2", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.407831000000101, -0.284649 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 004 Melintang", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.408086, -0.283388 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SMP Negeri 1 Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "3", "REMARK": "Pendidikan Menengah Pertama", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "2", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.485395, -0.316582 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 005 Enggelam", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.19176, -0.111317 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 005 Enggelam", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.224614, -0.115148 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 05 Muaraenggelam", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.328394000000117, -0.243881 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SMP Negeri 3 Muaraenggelam", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "3", "REMARK": "Pendidikan Menengah Pertama", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "2", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.327862, -0.244025 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 018 Kotabangun", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.536777038000082, -0.427421992999939 ] } },
{ "type": "Feature", "properties": { "NAMOBJ": "SD Negeri 010 Muarawis", "LUAS": 0.0, "KATPDK": "0", "JLPDDK": "0", "FGGPDK": "4", "REMARK": "Pendidikan Dasar", "FCODE": null, "SRS_ID": null, "LCODE": "GE0020", "METADATA": null, "JJGPDF": "1", "JNSPDL": "0" }, "geometry": { "type": "Point", "coordinates": [ 116.500769975000026, -0.429786024999942 ] } }
]
}
